# Generated by Django 5.2 on 2025-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('fullname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
