# Generated by Django 5.2 on 2025-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
